### ISSUE TITLE
Can't use connections part

### ISSUE THREAD

**Issue by stormtroober** [thfries/ditto-ui-bs4#2]
I have a 401 Unauthorized error when i try to access to "connections".
Things and Policy are correctly accessible, and the connections also works. 
Running a "default" configuration of ditto, tried also to Authorize, but nothing changed.

**Comment by thfries** [comment]
Hello aleshark87,

for the connections, the ditto devops api is used. The default config of ditto uses a different username here.
Please try devops:foobar instead of ditto:ditto to work with connections (see also [devops-commands](https://www.eclipse.org/ditto/installation-operating.html#devops-commands) ). You could create a copy of the "local_ditto" environment with a different username/pw to switch back and forth.

I found and fixed a bug when creating a new connection in ditto, so please pull the latest version.

Unfortunately I do not get connections fully work on my local ditto right now. If connections on your local ditto work, please try and let me know. I'll continue investigating.

**Comment by thfries** [comment]
I was able to test with ditto 2.4.0-M1 instead of latest, and that worked out.

**Comment by stormtroober** [comment]
Also for me is resolved now, but i would create a different page for authenticating on connections. It shouldn't be shared with the "local ditto authorization".

**Comment by thfries** [comment]
Hi aleshark87,
meanwhile, I added support for a separate user for the devOps api (for connections). So you can easily switch between Things, Policies and Connections.
